const List<String> dummyComments = [
  "I love it! <3",
  "HAahha",
  "ale zajebiste lol xd",
  "that's my favourite",
  "Make more PLEASE!!!",
  "I realy LOVE your content <3",
  "hi",
  "wanna meet up?",
  "check your DM's",
  "lol! this one is cool",
  "💘💘💘💘💘💘💘💘💘💘💘💘💘💘💘💘💘💘💘😘😘😘😘",
  "❤️🙌🔥Beautiful stylish, sweet, lovely",
  "Du scheinst dem Profil zu entsprechen, das ich finden sollte.",
  "Halloo",
  "Serwus",
  "Very natural pretty ❤️❤️❤️",
  "chеck уоur DM’s( hiddn )",
  "Ты хорошенькая",
  "Милашка",
  "If you're interested, please message our main account @rockdarkdream ☠️",
  "سلام",
  "do you need a sugar daddy to spoil?"
];
