name: instagram_clone_ui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  flutter_staggered_grid_view: ^0.6.2
  cached_network_image: ^3.2.3
  video_player: ^2.5.1
  flick_video_player: 0.5.0
  font_awesome_flutter: ^10.4.0
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Billabong
      fonts:
        - asset: fonts/billabong.ttf
    - family: BlueVinyl
      fonts:
        - asset: fonts/blue_vinyl_regular.otf
